# Generated by Django 3.2 on 2023-05-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='response',
        ),
    ]
